module.exports = {
  someSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Sharing',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/分享',
        title: 'Sharing',
        description:
          'Sharing.',
      },
      items: [
        '分享/不确定性',
        '分享/法律常识',
        '分享/健康延寿指南',
        '分享/十本书',
        '分享/emoji',
        '分享/AI工具',
        '分享/认知负荷是关键',
        '分享/resilio-sync',
        '分享/MrBeast',
        '分享/不确定性',
        '分享/自我管理',
        '分享/Done_is_better_than_Perfection',
        '分享/Experience_sharing',
        '分享/Nat_Friedman',
        '分享/自救指南',
        '分享/人人都是施b辰',
        '分享/翻墙',
        '分享/好玩的网站、工具',
      ],
    },
    {
      type: 'category',
      label: '读书笔记',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/读书笔记',
        title: '读书笔记',
        description:
          'Reading notes.',
      },
      items: [
        '读书笔记/西方现代思想讲义',
        '读书笔记/非暴力沟通',
        '读书笔记/Reality_Is_Broken',
        '读书笔记/Steal_Like_an_Artist',
        '读书笔记/一课经济学',
        '读书笔记/战略论-间接路线',
        '读书笔记/how_bad_do_you_want_it',
        '读书笔记/The_Modern_Mind',
        '读书笔记/what_is_our_problem',
        '读书笔记/微观经济学',
      ],
    },
    {
      type: 'category',
      label: '码农',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/码农',
        title: '码农',
        description:
          'Coding.',
      },
      items: [
        '码农/八股文/基础知识',
        '码农/八股文/面试题',
        '码农/刷题记录/数组',
        '码农/刷题记录/链表',
        '码农/刷题记录/哈希表',
        '码农/刷题记录/字符串',
        '码农/刷题记录/双指针',
        '码农/刷题记录/栈与队列',
        '码农/刷题记录/二叉树',
        '码农/刷题记录/回溯',
        '码农/刷题记录/贪心算法',
        '码农/刷题记录/动态规划',
        '码农/刷题记录/单调栈',
        '码农/刷题记录/图论',
        '码农/刷题记录/高级数据结构',
        '码农/刷题记录/其他',
        '码农/转码',
      ],
    },
  ],
};
