module.exports = {
  someSidebar: [
    'intro',
    {
      type: 'category',
      label: '分享',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/分享',
        title: 'Sharing',
        description: 'Sharing.',
      },
      items: [
        '分享/收藏',
        'archived/目录',        
        '分享/windows快捷键',
        '分享/让你吐槽不断的书',
        '分享/经济学小故事',
        '分享/不确定性',
        '分享/法律常识',
        '分享/健康延寿指南',
        '分享/十本书',
        '分享/emoji',
        '分享/AI工具',
        '分享/认知负荷是关键',
        '分享/resilio-sync',
        '分享/MrBeast',
        '分享/不确定性',
        '分享/自我管理',
        '分享/Done_is_better_than_Perfection',
        '分享/Experience_sharing',
        '分享/Nat_Friedman',
        '分享/好玩的网站、工具',
      ],
    },
    {
      type: 'category',
      label: '读书笔记',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/读书笔记',
        title: '读书笔记',
        description: 'Reading notes.',
      },
      items: [
        '读书笔记/百面机器学习',
        '读书笔记/西方现代思想讲义',
        '读书笔记/非暴力沟通',
        '读书笔记/Reality_Is_Broken',
        '读书笔记/Steal_Like_an_Artist',
        '读书笔记/一课经济学',
        '读书笔记/战略论-间接路线',
        '读书笔记/how_bad_do_you_want_it',
        '读书笔记/The_Modern_Mind',
        '读书笔记/what_is_our_problem',
        '读书笔记/微观经济学',
        '读书笔记/学会提问--批判性思维指南',
      ],
    },
    {
      type: 'category',
      label: '技巧',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/技巧',
        title: '技巧',
        description: 'Tips.',
      },
      items: [
        '技巧/域名注册解析',
        '技巧/conda管理python',
        '技巧/Github搜索技巧',
        '技巧/Hexo版本升级指南',
        '技巧/MarkdownSyntax',
        '技巧/提问躺枪',
        '技巧/提高chrome使用效率',
        '技巧/Github搜索技巧',
      ],
    },
    {
      type: 'category',
      label: '数学',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/数学',
        title: '数学',
        description: 'Mathematics.',
      },
      items: [
        '数学/似然函数',
        '数学/LDA、PCA',
        '数学/奇异值分解',
        '数学/Latex常用数学符号',
        '数学/散度',
        '数学/矩阵',
      ],
    },
    {
      type: 'category',
      label: '思考',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/思考',
        title: '思考',
        description: 'Thinking.',
      },
      items: [
        '思考/如何选择',
        '思考/小故事',
        '思考/人间是否值得',
        '思考/不要再忽悠孩子了',
        '思考/蓝眼睛和红眼睛',
      ],
    },
    {
      type: 'category',
      label: '学习',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/学习',
        title: '学习',
        description: 'Learning.',
      },
      items: [
        '周报/index',
        '学习/我的八股',
        '学习/工程矩阵/工程矩阵笔记',
        '学习/DOA估计',
        '学习/克拉美-罗界',
        '学习/Csi-feedback',
        '学习/通信笔记',
        '学习/DFT',
        '学习/信息论基础',
      ],
    },
    {
      type: 'category',
      label: '码农',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/码农',
        title: '码农',
        description: 'Coding.',
      },
      items: [
        '码农/Wake-Up',
        '码农/deep_learning/index',
        '码农/刷题记录/index',
        '码农/java笔记',
        '码农/Java学习路线',
        '码农/计算机信息差',
        '码农/转码',
        '码农/How_browsers_work',
      ],
    },
    {
      type: 'category',
      label: '毛选',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/毛选',
        title: '毛选',
        description: 'Selection.',
      },
      items: ['毛选/目录'],
    },
  ],
};
