apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mybook-star
  namespace: mybook
  labels:
    app: mybook
spec:
  secretName: mybook-star-tls
  dnsNames:
    - "*.mybook.chia.net"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cf
