name: blog-post-workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 */1 * * *' # Runs every hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG"
          feed_list: "https://onojyun.com/feed/,http://feeds.feedburner.com/ruanyifeng/,https://stephenleng.com/cn/rss,https://lozhu.happy365.day/atom.xml,https://feeds.feedburner.com/initiative,https://codechina.org/feed/"
          feed_names: "onojyun,ruanyifeng,stephenleng,lozhu,est,Tinyfool"
          date_format: 'mmm d, yyyy'
          readme_path: "./docs/intro.md"
          max_post_count: 30
          template: '$newline<li style="padding-left: 20px;"><a href="$url">$title</a>- by $feedName - $date</li>'