name: blog-post-workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 */3 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG"
          feed_list: "https://onojyun.com/feed/,https://terrytao.wordpress.com/feed/,http://feeds.feedburner.com/ruanyifeng/,https://hsu.cy/feed.xml,https://weekly.1q43.blog/rss/feed.xml,https://stephenleng.com/cn/rss,https://zhangluyao.com/index.xml"
          feed_names: "onojyun,terrytao,ruanyifeng,hsu,1q43,stephenleng,zhangluyao"
          date_format: 'mmm d, yyyy'
          readme_path: "./docs/intro.md"
          max_post_count: 30
          template: $newline<li><a href="$url">$title</a>- by $feedName - $date