name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["blog-post-workflow"] # 替换为你想监听的工作流名称
    types:
      - completed

# on:
#   push:
#     branches:
#       - main
#     # Review gh actions docs if you want to further define triggers, paths, etc
#     # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Build website
        run: NODE_OPTIONS="--max-old-space-size=4096" npm run build
      
      #old
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     # Build output to publish to the `gh-pages` branch:
      #     publish_dir: ./build
      #     # The following lines assign commit authorship to the official
      #     # GH-Actions bot for deploys to `gh-pages` branch:
      #     # https://github.com/actions/checkout/issues/13#issuecomment-724415212
      #     # The GH actions bot is used by default if you didn't specify the two fields.
      #     # You can swap them out with your own user credentials.
      #     user_name: LiWen
      #     user_email: 175311843+Liwen1234-cyber@users.noreply.github.com

      #new
      - name: 部署到公共仓库
        uses: peaceiris/actions-gh-pages@v3
        with:
          persist-credentials: true
          # Personal Access Token 下面讲 
          personal_token: ${{ secrets.PUBLISH_BLOG }}
          # 指定push的仓库  
          external_repository: Liwen1234-cyber/mywebsite
          # 指定push的分支
          publish_branch: main
          # push 的目录
          publish_dir: ./build
          # 是否只保留最新的提交记录
          force_orphan: true
          user_name: LiWen
          user_email: 175311843+Liwen1234-cyber@users.noreply.github.com

        # run: |
        #   echo "doc.minddiy.top" > CNAME
        #   git init
        #   git checkout -b gh-pages
        #   git add -A
        #   git -c user.name='LiWen' -c user.email='175311843+Liwen1234-cyber@users.noreply.github.com' commit -m 'new' 
        #   git remote add origin https://${{secrets.PUBLISH_BLOG}}@github.com/Liwen1234-cyber/mywebsite.git
        #   git push origin gh-pages -f -q