# old
# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main
#     # Review gh actions docs if you want to further define triggers, paths, etc
#     # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

# permissions:
#   contents: write

# jobs:
#   deploy:
#     name: Deploy to GitHub Pages
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           cache: npm

#       - name: Install dependencies
#         run: npm install --frozen-lockfile
#       - name: Build website
#         run: npm run build

#       # Popular action to deploy to GitHub Pages:
#       # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           # Build output to publish to the `gh-pages` branch:
#           publish_dir: ./build
#           # The following lines assign commit authorship to the official
#           # GH-Actions bot for deploys to `gh-pages` branch:
#           # https://github.com/actions/checkout/issues/13#issuecomment-724415212
#           # The GH actions bot is used by default if you didn't specify the two fields.
#           # You can swap them out with your own user credentials.
#           user_name: LiWen
#           user_email: 175311843+Liwen1234-cyber@users.noreply.github.com

# new
name: Deploy Site
on:
  push:
   branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
      persist-credentials: true # false 是用 personal token，true 是使用 GitHub token
      fetch-depth: 0

    - name: Commit and Push
      working-directory: public
      run: |
        echo "doc.minddiy.top" > CNAME
        git init
        git checkout -b gh-pages
        git add -A
        git -c user.name='LiWen' -c user.email='175311843+Liwen1234-cyber@users.noreply.github.com' commit -m 'new' 
        git remote add origin https://github.com/Liwen1234-cyber/mywebsite.git
        git push origin gh-pages -f -q