name: Generate RSS

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/generate-rss.yml'
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate RSS
      run: python generate_rss.py
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "175311843+Liwen1234-cyber@users.noreply.github.com"
        git config --local user.name "LiWen"
        git add static/rss.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feed" && git push) 