name: Latest-YouTube-Videos
on:
  schedule: # Run workflow automatically
    - cron: '59 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in latest YouTube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: 'YOUTUBE'
          feed_list: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCrMjr7dY8syS_m9TdqM-g_Q,https://www.youtube.com/feeds/videos.xml?channel_id=UC2ggjtuuWvxrHHHiaDH1dlQ'
          feed_names: 'Mr Li, Hung-yi Lee'
          readme_path: './docs/intro.md'
          custom_tags: 'channelId/yt:channelId/,videoId/yt:videoId/'
          date_format: 'mmm d, yyyy'
          template: '$newline<tr><td><a href="$url"><img width="200px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>$newline<td><a href="$url">$title</a></td>$newline<td>$date</td></tr>'
          max_post_count: 10
